### ISSUE TITLE
slamhound.el doesn't support cider versions 0.8.0+

### ISSUE THREAD

**Issue by lsankar4033** [technomancy/slamhound#92]
If you take a look at the [changelog](https://github.com/clojure-emacs/cider/blob/77a3985e54957fc3368ea313af22c602531a7601/CHANGELOG.md), Cider renamed `nrepl-send-string-sync` to `nrepl-sync-request`.  I believe this just involves a 1 line change [here](https://github.com/technomancy/slamhound/blob/f43dd49b63b2838081735ea1988f70de05389692/slamhound.el#L60).

I can submit a PR when I get a chance.

**Comment by piotrklibert** [comment]
I fixed this in https://github.com/technomancy/slamhound/pull/93 and also rewrote the command to be asynchronous.
